name: "Telebot Runner"
on:
  push:
  schedule:
    - cron: '0 * * * *'
  pull_request:
  schedule:
    - cron: '0 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: get/install python
        uses: actions/checkout@v2
        uses: actions/setup-python@v3
      - name: Install requirements
        run: |
          pip3 install pytelegrambotapi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run main.py
        run: python3 main.py
#        env:
#          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
#          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID  }}
